### ISSUE TITLE
AESTHETICS - Logo

### ISSUE THREAD

**Issue by OmniStingray** [blakestone95/AshkeepersRestWebsite#3]
Jeffry and me need to work on logos

**Comment by IsNOTJeremy** [comment]
We hope to base our icon logo on the style of military Distinctive Unit Insignia. https://en.wikipedia.org/wiki/Distinctive_unit_insignia
If anyone has any thoughts on imagery or elements, let Sam and I know.

**Comment by blakestone95** [comment]
How far have you guys gotten on this?  I looked at the Wikipedia page and though of an idea:
- Shield shape
- 3 weapon silhouette cross with each weapon from a different era (i.e. sword, modern assault rifle (like M16), futuristic gun (like iconic Halo assault rifle))
![image](https://user-images.githubusercontent.com/7433264/40863198-cce43ed6-65a3-11e8-9d0e-c868e326f607.png)
 ^ Cross weapons like how the torches are crossed in this one
- Words "per unitatem fortitudinem" in a U-shaped banner (since the words are a little long) that goes around and below the weapons (this means "strength through unity" in Latin).

Like?  No like?

**Comment by IsNOTJeremy** [comment]
Sounds like some really good ideas! So, you think "Per Unitatem Fortitudinem" would be a good phrase? I have no objections! Crossing the weapons is a common theme, I'll explore it some, though for the weapons I want to avoid directly copying anything, so we can use the logo for anything and not worry about legal issues. So far I've mostly looked at forms, and sketched some loose ideas, as time has been tight with projects coming due. Hopefully after next week I'll have a lot more time to work on this.

**Comment by OmniStingray** [comment]
Oh ok neat!  Yeah maybe I'll try something tomorrow.

**Comment by blakestone95** [comment]
Shield shape somewhat like this: 
![image](https://user-images.githubusercontent.com/7433264/41696675-19f35290-74ca-11e8-89a5-6f5a02ce1454.png)

**Comment by OmniStingray** [comment]
Current Iteration

![logo_melee](https://user-images.githubusercontent.com/15239866/41810685-7d369a26-76b7-11e8-8175-11780faf17b5.png)

**Comment by blakestone95** [comment]
For record purposes: We decided to go with an entirely different design idea that was more in-line with our goals as a community.  Instead, the new logo features a tree with the silhouette of a person resting against it with the backdrop of a setting sun.  The logo symbolizes the idea that our community is a place to lay down your burdens and relax for a while.
